# Generated by Django 5.2 on 2025-04-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consumption_time', models.DateField(verbose_name='消费产生时间')),
                ('Consumption', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='消费金额')),
                ('OtherInfo', models.TextField(verbose_name='额外说明')),
            ],
        ),
    ]
