# Generated by Django 5.2 on 2025-04-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='Consumption_type',
            field=models.SmallIntegerField(choices=[(0, '其他'), (1, '购物'), (2, '餐饮')], default=0, verbose_name='消费类型'),
        ),
        migrations.AlterField(
            model_name='money',
            name='Consumption_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='OtherInfo',
            field=models.TextField(blank=True, null=True, verbose_name='额外说明'),
        ),
    ]
