# Generated by Django 5.2 on 2025-04-04 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0003_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='Consumption_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='消费时间'),
        ),
    ]
