# Generated by Django 5.2 on 2025-04-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0004_alter_money_consumption_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='debt',
        ),
        migrations.AddField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=7, verbose_name='借款利息'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='name',
            field=models.TextField(default=0, verbose_name='借款对象'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='借款本金'),
            preserve_default=False,
        ),
    ]
