# Generated by Django 5.2 on 2025-04-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0005_remove_loan_debt_loan_interest_loan_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='principal',
        ),
    ]
