# Generated by Django 5.2 on 2025-04-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0007_loan_interest_loan_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='Tobepaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='每月待还'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='name',
            field=models.TextField(verbose_name='债务名称'),
        ),
    ]
