name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  USER: "${{ secrets.DOCKERNAME }}"
  PASS: "${{ secrets.DOCKERPASS}}"
  REGISTRY: "${{ secrets.DOCKERLINE }}"
  NAMESPACE: "${{ secrets.DOCKERNS }}"


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $REGISTRY/$NAMESPACE/monerymanager:1.0.0

    - name: push docker image
      run: |
        docker login -u $USER -p $PASS $REGISTER
        docker push $REGISTRY/$NAMESPACE/monerymanager:1.0.0
