name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  version: 1.0.1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.REGISTRY }}/monerymanager:${{ env.version }}



    - name: Authenticate to registry ${{ secrets.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: push docker image
      run: |
        docker push ${{ secrets.REGISTRY }}/monerymanager:${{ env.version }}